# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
matrix:
  include:
  - os: linux
    dist: trusty
    r: release
    apt_packages: libicu-dev
  - os: linux
    dist: trusty
    r: oldrel
    r_build_args: "--no-manual"
    r_check_args: "--no-manual"
    apt_packages: libicu-dev
  - os: linux
    dist: trusty
    r: devel
    apt_packages: libicu-dev
  - os: linux
    dist: trusty
    r: devel
  - os: osx
    r: release
  - os: osx
    r: devel

warnings_are_errors: true
sudo: required
